import './styles.css';

const $ = s => document.querySelector(s);
const today = () => new Date().toISOString().slice(0,10);
const clamp = (n,a,b) => Math.max(a,Math.min(b,n));
const seed = () => ({
  screen:'title', reality:false, energy:'normal', autonomy:'balanced',
  hero:{name:'Aerin',archetype:'Pathfinder',level:3,xp:170,nextXp:260,coins:128,shards:7,stats:{Vitality:7,Focus:8,Courage:6,Craft:7,Connection:6}},
  goal:'Build a stronger, more creative, more intentional life',
  arcs:['Move consistently','Finish meaningful creative work'],
  ship:{name:'The Wayfarer',heart:28,level:2,rooms:[['Common Deck',2,'🔥'],['Navigation Room',2,'🗺️'],['Workshop',1,'⚙️'],['Garden Deck',1,'🌿'],['Archive',0,'📚'],['Crystal Heart',1,'💠']]},
  companions:[
    {id:'kaia',name:'Kaia',img:'./assets/kaia.svg',role:'Fighter & Pathfinder',mood:'Focused',hook:'Her living map redraws itself around your choices.',perk:'Mapmaker: stronger progress on planned quests.'},
    {id:'milo',name:'Milo',img:'./assets/milo.svg',role:'Scout & Trickster',mood:'Restless',hook:'Bonded to Flick, a tiny shapeshifting spirit.',perk:'Lucky Find: improved unusual reward chance.'},
    {id:'seren',name:'Seren',img:'./assets/seren.svg',role:'Mage & Listener',mood:'Curious',hook:'She senses echoes of unfinished intentions.',perk:'Echo Sense: surfaces neglected quest arcs.'}
  ],
  enemies:[
    {id:'drift',name:'Driftling Pack',glyph:'👾',rep:'Tiny distractions',hp:34,max:50},
    {id:'wraith',name:'Hesitation Wraith',glyph:'👻',rep:'Delay that grows when fed',hp:88,max:120},
    {id:'tangle',name:'The Tangleback',glyph:'🌿',rep:'Unfinished mental clutter',hp:70,max:90}
  ],
  quests:[
    {id:'q1',kind:'MAIN',title:'Open the Road',desc:'Spend 20 focused minutes on the action that moves your primary goal forward.',tiny:'Open the work and stay with it for 2 minutes.',stat:'Focus',effort:20,xp:35,coins:12,enemy:'wraith',done:false,scaled:0},
    {id:'q2',kind:'SIDE',title:'Walk the Amber Ridge',desc:'Move your body for 15 minutes in any way that fits today.',tiny:'Stand, stretch, and move for 60 seconds.',stat:'Vitality',effort:15,xp:28,coins:10,enemy:'drift',done:false,scaled:0},
    {id:'q3',kind:'SIDE',title:'Signal the Fellowship',desc:'Reach out to one person you value.',tiny:'Send one warm sentence.',stat:'Connection',effort:5,xp:20,coins:8,enemy:'drift',done:false,scaled:0},
    {id:'q4',kind:'MICRO',title:'First Spark',desc:'Choose a tiny reset: water, breath, movement, or a written intention.',tiny:'One deliberate breath counts.',stat:'Courage',effort:2,xp:14,coins:5,enemy:'drift',done:false,scaled:0},
    {id:'q5',kind:'HIGH STAKES',title:'Face the Unfinished Door',desc:'Do the task you have been avoiding most.',tiny:'Name it and write the next action.',stat:'Courage',effort:35,xp:65,coins:24,enemy:'wraith',done:false,scaled:0}
  ],
  inventory:[
    {name:'Lens of Stillness',glyph:'🔮',rarity:'Rare Relic',desc:'The first focused quest each day earns bonus XP.'},
    {name:'Windglass Shard',glyph:'💎',rarity:'Uncommon',desc:'A crystal fragment from the ship’s sleeping engine.'},
    {name:'Amber Thread',glyph:'🧵',rarity:'Common',desc:'Used by the Workshop to restore sail-runes.'}
  ],
  skills:[['Momentum','Focus',true],['Gentle Path','Vitality',true],['Kinship','Connection',false],['Iron Will','Courage',false],['Living Route','Craft',false],['Starwake','Craft',false]],
  chat:[{who:'Seren',text:'The ship remembers motion, not perfection. What do you want to move today?'}],
  journal:[{day:today(),title:'The Heart Stirred',text:'A pulse moved through the old ship. Kaia’s map drew a road where there had been only cloud.',milestone:true}],
  daily:{date:today(),completed:[],xp:0,coins:0}, prologue:0
});
let state = (()=>{try{return {...seed(),...JSON.parse(localStorage.getItem('ascendant-save'))}}catch{return seed()}})();
const save=()=>localStorage.setItem('ascendant-save',JSON.stringify(state));
const toast=msg=>{const n=document.createElement('div');n.className='toast';n.textContent=msg;$('#toast').append(n);setTimeout(()=>n.remove(),2200)};
const setScreen=s=>{state.screen=s;save();render();scrollTo({top:0,behavior:'smooth'})};
const nav=()=>`<nav class="dock">${[['today','⚔️','Today'],['world','🗺️','World'],['ship','⛵','Ship'],['hero','🛡️','Hero'],['gm','✨','GM']].map(([s,i,l])=>`<button data-screen="${s}" class="${state.screen===s?'active':''}"><b>${i}</b><span>${l}</span></button>`).join('')}</nav>`;
const heroBar=()=>`<header class="glass hero"><div><small>CHAPTER 2 · ${state.hero.archetype}</small><h2>${state.hero.name} <span>Lv ${state.hero.level}</span></h2><div class="xp"><i style="width:${state.hero.xp/state.hero.nextXp*100}%"></i></div></div><div class="resources">🪙 ${state.hero.coins} &nbsp; ✦ ${state.hero.shards}<button id="lens" class="ghost">${state.reality?'Hide Lens':'Reality Lens'}</button></div></header>`;
const reality=()=>state.reality?`<section class="glass reality"><small>REALITY LENS</small><h3>${state.goal}</h3><p>Primary campaign anchor. Side arcs: ${state.arcs.join(' · ')}. AI autonomy: ${state.autonomy}. Today’s energy: ${state.energy}.</p></section>`:'';
function completeQuest(id){const q=state.quests.find(x=>x.id===id);if(!q||q.done)return;q.done=true;state.daily.completed.push(id);let xp=q.xp,coins=q.coins;state.hero.xp+=xp;state.hero.coins+=coins;state.daily.xp+=xp;state.daily.coins+=coins;const e=state.enemies.find(x=>x.id===q.enemy);const dmg=Math.round(12+q.xp/3+(q.kind==='HIGH STAKES'?12:0));if(e)e.hp=Math.max(0,e.hp-dmg);state.ship.heart=clamp(state.ship.heart+Math.round(q.xp/6),0,100);if(state.hero.xp>=state.hero.nextXp){state.hero.level++;state.hero.xp-=state.hero.nextXp;state.hero.nextXp=Math.round(state.hero.nextXp*1.28)};if(Math.random()<.35)state.hero.shards++;state.journal.unshift({day:today(),title:q.title,text:`${q.title} landed a ${dmg}-point strike on ${e?.name||'the darkness'}.`,milestone:q.kind==='HIGH STAKES'});save();battle(q,e,dmg,xp,coins)}
function scaleQuest(id){const q=state.quests.find(x=>x.id===id);if(!q)return;q.scaled++;q.effort=Math.max(1,Math.round(q.effort*.55));toast('Quest scaled down. Story progress is unchanged.');save();render()}
function battle(q,e,dmg,xp,coins){const o=document.createElement('div');o.className='overlay';o.innerHTML=`<div class="battle glass"><small>REAL ACTION → PARTY STRIKE</small><div class="enemyGlyph">${e?.glyph||'✨'}</div><div class="damage">-${dmg}</div><h1>${e&&e.hp===0?`${e.name} defeated!`:'A clean hit.'}</h1><p>Your real-world action powered the attack.</p><div class="combos"><span>🛡️ Kaia: Guard</span><span>🦊 Milo: Find</span><span>🔮 Seren: Insight</span></div><p><b>+${xp} XP</b> · <b>+${coins} coins</b> · Crystal Heart ${state.ship.heart}%</p><button class="primary" id="continue">Continue</button></div>`;document.body.append(o);$('#continue').onclick=()=>{o.remove();render()}}
function title(){return `<main class="titleScreen"><img src="./assets/ship.svg" alt="The Wayfarer skyship"><div class="titleCard glass"><small>THE REAL-LIFE RPG</small><h1>ASCENDANT</h1><p>Your goals become quests. Your obstacles become foes. Your real actions change the world.</p><button class="primary" id="start">${state.prologue?'Continue Campaign':'Begin the Silent Drift'}</button></div></main>`}
function prologue(){const steps=[
['Silent Drift','The Wayfarer hangs powerless above an endless sea of cloud. Kaia studies a map that has gone blank. Milo has stopped joking. Seren is listening to something below deck.'],
['The Fall Begins','The ship shudders. Altitude is dropping. Seren turns toward the dark stairwell: “The heart is still there. Sleeping.”'],
['Choose Your First Spark','Pick one tiny action in the real world. It does not need to be impressive. It only needs to be real.'],
['The Heart Answers','Light races through the deck. Kaia anchors the sails. Milo and Flick free a jammed wing-rune. Seren places a hand against the crystal core. The clouds below begin to split.']
];const [t,p]=steps[state.prologue]||steps[0];const choices=state.prologue===2?`<div class="spark">${['💧 Drink water','🌬️ Take one deliberate breath','🚶 Move for one minute','✍️ Write one intention'].map(x=>`<button class="sparkBtn">${x}</button>`).join('')}</div>`:`<button class="primary" id="nextPrologue">${state.prologue===3?'Reveal the Amber Highlands':'Continue'}</button>`;return `<main class="prologue"><div class="scene"><img src="./assets/ship.svg" alt="Wayfarer above the clouds"></div><section class="glass story"><small>PROLOGUE</small><h1>${t}</h1><p>${p}</p>${choices}</section></main>`}
function todayScreen(){const qs=state.quests.filter(q=>!q.done);return `<main class="page">${heroBar()}${reality()}<section class="glass dailyBeat"><small>TODAY’S STORY BEAT</small><h2>The Amber road is open, but the Wraith is moving again.</h2><div class="energy">${['low','normal','high'].map(e=>`<button data-energy="${e}" class="${state.energy===e?'active':''}">${e} energy</button>`).join('')}</div></section><section><div class="sectionTitle"><div><small>YOUR RUN</small><h1>Choose the next strike</h1></div><span>${state.daily.completed.length} completed</span></div><div class="quests">${qs.map(q=>`<article class="glass quest"><div><small>${q.kind} · ${q.stat}</small><h3>${q.title}</h3><p>${q.scaled?q.tiny:q.desc}</p><em>~${q.effort} min · +${q.xp} XP · +${q.coins} coins</em></div><div class="actions"><button class="primary strike" data-id="${q.id}">Strike</button><button class="ghost scale" data-id="${q.id}">Make smaller</button></div></article>`).join('')||'<div class="glass empty"><h2>Today’s road is clear.</h2><p>Return to the ship for the evening ritual.</p></div>'}</div></section><section><div class="sectionTitle"><div><small>ACTIVE THREATS</small><h1>Foes</h1></div></div><div class="foes">${state.enemies.map(e=>`<article class="glass foe"><div class="glyph">${e.glyph}</div><h3>${e.name}</h3><p>${e.rep}</p><div class="hp"><i style="width:${e.hp/e.max*100}%"></i></div><small>${e.hp}/${e.max}</small></article>`).join('')}</div></section>${nav()}</main>`}
function world(){return `<main class="page">${heroBar()}<section class="worldHero glass"><small>REGION I</small><h1>The Amber Highlands</h1><p>Golden grasslands give way to impossible ruins, luminous forest pockets, and fragments of sky-islands drifting above the old roads.</p><div class="map"><div class="route"></div>${[['Ship',12,72,'⛵'],['Ridge',30,58,'⚔️'],['Ruins',49,49,'🏛️'],['Glowwood',67,35,'🌲'],['Wraith Gate',84,22,'👻']].map(([n,x,y,g])=>`<div class="node" style="left:${x}%;top:${y}%"><b>${g}</b><span>${n}</span></div>`).join('')}</div></section><section class="grid2"><div class="glass card"><small>LIVING WORLD</small><h2>What changes here</h2><p>Real-world progress opens routes, restores settlements, changes weather, reveals secrets, and weakens threats.</p></div><div class="glass card"><small>REALITY LENS</small><h2>Campaign mapping</h2><p>Primary arc: ${state.goal}. Side arcs: ${state.arcs.join(' · ')}.</p></div></section>${nav()}</main>`}
function ship(){return `<main class="page">${heroBar()}<section class="shipHero glass"><img src="./assets/ship.svg" alt="The Wayfarer"><div><small>GROWING HOME BASE</small><h1>${state.ship.name}</h1><p>A warm enchanted vessel built around an older machine. The more you progress, the more the ship remembers what it really is.</p><div class="heart"><span>Crystal Heart</span><div><i style="width:${state.ship.heart}%"></i></div><b>${state.ship.heart}%</b></div></div></section><section class="rooms">${state.ship.rooms.map(([n,l,g])=>`<article class="glass room ${l===0?'locked':''}"><b>${g}</b><div><small>${l===0?'SEALED':`RESTORATION ${l}`}</small><h3>${n}</h3></div></article>`).join('')}</section><section><div class="sectionTitle"><div><small>THE WAYFARERS</small><h1>Your traveling party</h1></div></div><div class="party">${state.companions.map(c=>`<article class="glass companion"><img src="${c.img}" alt="${c.name}"><div><small>${c.role}</small><h3>${c.name}</h3><p>${c.hook}</p><em>${c.perk}</em></div></article>`).join('')}</div></section>${nav()}</main>`}
function hero(){return `<main class="page">${heroBar()}<section class="grid2"><article class="glass card heroCard"><small>EVOLVING IDENTITY</small><h1>${state.hero.name}, ${state.hero.archetype}</h1><p>Your class is not fixed. Your actual choices, relics, relationships, and skill investments determine what you become.</p>${Object.entries(state.hero.stats).map(([k,v])=>`<div class="stat"><span>${k}</span><b>${v}</b></div>`).join('')}</article><article class="glass card"><small>SKILL PATHS</small><h2>Awakened abilities</h2>${state.skills.map(([n,s,u])=>`<div class="skill ${u?'on':''}"><b>${u?'✦':'◇'} ${n}</b><span>${s}</span></div>`).join('')}</article></section><section><div class="sectionTitle"><div><small>TREASURE</small><h1>Relics & materials</h1></div></div><div class="inventory">${state.inventory.map(i=>`<article class="glass relic"><div>${i.glyph}</div><small>${i.rarity}</small><h3>${i.name}</h3><p>${i.desc}</p></article>`).join('')}</div></section>${nav()}</main>`}
function gm(){return `<main class="page">${heroBar()}<section class="grid2"><article class="glass card"><small>ADAPTIVE CAMPAIGN DIRECTOR</small><h1>The GM Ensemble</h1><p>One coherent intelligence expressed through the Wayfarers and guild specialists. Routine campaign content is automatic; major changes stay transparent and reversible.</p><label>AI autonomy<select id="autonomy"><option ${state.autonomy==='conservative'?'selected':''}>conservative</option><option ${state.autonomy==='balanced'?'selected':''}>balanced</option><option ${state.autonomy==='director'?'selected':''}>director</option></select></label></article><article class="glass card"><small>QUICK ACTIONS</small><div class="quick">${['Give me a tiny quest','Create a boss encounter','Recap my story','Explain today’s quests'].map(x=>`<button class="ghost prompt">${x}</button>`).join('')}</div></article></section><section class="glass chat"><div id="messages">${state.chat.map(m=>`<div class="bubble"><b>${m.who}</b><p>${m.text}</p></div>`).join('')}</div><form id="chatForm"><input id="chatInput" placeholder="Ask the Wayfarers..." autocomplete="off"><button class="primary">Send</button></form></section><section><div class="sectionTitle"><div><small>LIVING CHRONICLE</small><h1>Captain’s Log</h1></div></div>${state.journal.slice(0,5).map(j=>`<article class="journal ${j.milestone?'milestone':''}"><small>${j.day}</small><h3>${j.title}</h3><p>${j.text}</p></article>`).join('')}</section><section class="glass card settings"><h2>Save & portability</h2><button id="export" class="ghost">Export save</button><label class="ghost file">Import save<input id="import" type="file" accept="application/json"></label></section>${nav()}</main>`}
function render(){const app=$('#app');app.innerHTML=state.screen==='title'?title():state.screen==='prologue'?prologue():state.screen==='world'?world():state.screen==='ship'?ship():state.screen==='hero'?hero():state.screen==='gm'?gm():todayScreen();bind()}
function bind(){document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>setScreen(b.dataset.screen));$('#lens')&&($('#lens').onclick=()=>{state.reality=!state.reality;save();render()});$('#start')&&($('#start').onclick=()=>{state.screen=state.prologue>=4?'today':'prologue';save();render()});$('#nextPrologue')&&($('#nextPrologue').onclick=()=>{state.prologue++;if(state.prologue>3){state.screen='today';state.prologue=4}save();render()});document.querySelectorAll('.sparkBtn').forEach(b=>b.onclick=()=>{toast(`${b.textContent} — the First Spark is real.`);state.prologue=3;state.ship.heart=35;save();render()});document.querySelectorAll('.strike').forEach(b=>b.onclick=()=>completeQuest(b.dataset.id));document.querySelectorAll('.scale').forEach(b=>b.onclick=()=>scaleQuest(b.dataset.id));document.querySelectorAll('[data-energy]').forEach(b=>b.onclick=()=>{state.energy=b.dataset.energy;save();render()});$('#autonomy')&&($('#autonomy').onchange=e=>{state.autonomy=e.target.value;save();toast('AI autonomy updated')});document.querySelectorAll('.prompt').forEach(b=>b.onclick=()=>gmReply(b.textContent));$('#chatForm')&&($('#chatForm').onsubmit=e=>{e.preventDefault();const input=$('#chatInput');if(input.value.trim())gmReply(input.value.trim(),true);input.value=''});$('#export')&&($('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='ascendant-save.json';a.click()});$('#import')&&($('#import').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state={...seed(),...JSON.parse(r.result)};save();render();toast('Campaign imported')}catch{toast('That save could not be read')}};r.readAsText(f)})}
function gmReply(text,fromPlayer=false){if(fromPlayer)state.chat.push({who:'You',text});let reply='';const t=text.toLowerCase();if(t.includes('tiny'))reply='Milo grins. “One minute. Open the thing you have been avoiding. No heroics. Just touch the road.”';else if(t.includes('boss'))reply='Kaia studies the living map. “The Wraith can become a boss when you choose a milestone worth defending.”';else if(t.includes('recap'))reply=`Seren: “You have completed ${state.daily.completed.length} quests today. The Crystal Heart is at ${state.ship.heart}%. The road is changing.”`;else if(t.includes('why')||t.includes('explain'))reply='Seren: “Each quest maps to your real campaign goals. Open the Reality Lens any time you want to see the machinery beneath the story.”';else reply='Seren listens for a moment. “I can turn that into a quest, make it smaller, or help decide which arc it belongs to.”';state.chat.push({who:'Wayfarers',text:reply});save();render()}

if('serviceWorker' in navigator) addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
